version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_dev
    restart: always
    env_file: .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_dev
    restart: always
    env_file: .env.dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    restart: always
    env_file: .env.dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
