version: "3.8"

services:
  db:
    image: postgres:15
    container_name: trustworks_db_prod
    restart: always
    environment:
      POSTGRES_DB: trustworks_prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: senha_segura
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - trustworks_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user -d trustworks_prod"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: trustworks_backend_prod
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trustworks_network
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn trustworks.wsgi:application --bind 0.0.0.0:8000 --workers=4"

networks:
  trustworks_network:

volumes:
  pgdata_prod:
